[tool.poetry]
name = "kaggle-titanic-machine-learning-from-disaster"
version = "0.1.0"
description = "Solução para o desafio Titanic ML no Kaggle: previsão de sobreviventes do naufrágio usando aprendizado de máquina. Inclui preparação de dados, testes com diferentes modelos e otimização de hiperparâmetros."
authors = ["Matheus Abrantes <abrantes_matheus@icloud.com>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.10"
pandas = "^1.3.3"
scikit-learn = "^1.0"
matplotlib = "^3.4.3"
seaborn = "^0.11.2"
xgboost = "^1.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
